[book]
authors = ["nilton-f-o-junior"]
language = "en"
src = "src"
title = "Rust Developer - Roadmap"

[output.html]
git-repository-url = "https://github.com/nilton-f-o-junior/rust-developer"
#git-repository-icon = "fa-github"
